version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - mkdir proto/go
      - protoc -I proto proto/*.proto --go_out=./proto/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/go/ --go-grpc_opt=paths=source_relative;